# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "octocat"
      - "johnkegd"
    commit-message:
      # Prefix all commit messages with "composer"
      prefix: "composer"
      include: "scope"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/app"
    schedule:
      interval: "daily"
    reviewers:
      - "octocat"
      - "johnkegd"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
      

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      # Add reviewers
    reviewers:
      - "octocat"
      - "johnkegd"
